const test=require('node:test'),assert=require('node:assert/strict');
const {wrap}=require('../lib/server');
function response(){return {code:200,headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.code=n;return this;},json(v){this.body=v;},end(){}};}
test('API rejects unsupported method before handler',async()=>{const r=response();await wrap(['POST'],()=>assert.fail())({method:'GET',headers:{}},r);assert.equal(r.code,405);});
test('untrusted origin cannot invoke mutation',async()=>{process.env.ALLOWED_ORIGINS='https://trusted.example';const r=response();await wrap(['POST'],()=>assert.fail())({method:'POST',headers:{origin:'https://attacker.example'}},r);assert.equal(r.code,403);});
test('official GitHub Pages origin is allowed by default',async()=>{delete process.env.ALLOWED_ORIGINS;const r=response();await wrap(['POST'],()=>r.status(200).json({ok:true}))({method:'POST',headers:{origin:'https://juansenaff.github.io'}},r);assert.equal(r.code,200);assert.equal(r.headers['Access-Control-Allow-Origin'],'https://juansenaff.github.io');});
test('state validator rejects corrupt skill and malformed payloads',()=>{const {valid}=require('../api/state');assert.equal(valid({}),false);assert.equal(valid({profile:{x:{l:9,e:0}},prefs:{},applications:{},answers:{},alertRules:{},history:[],skillHistory:[],dismissed:[]}),false);});
test('state validator rejects malformed historical match snapshot',()=>{const {valid}=require('../api/state'),state={profile:{x:{l:1,e:1}},prefs:{},applications:{a:{matchSnapshot:{version:1,score:999}}},answers:{},alertRules:{},history:[],skillHistory:[],dismissed:[]};assert.equal(valid(state),false);});
test('state validator accepts structured evidence and rejects unsafe links',()=>{const {valid}=require('../api/state'),base={prefs:{},applications:{},answers:{},alertRules:{},history:[],skillHistory:[],dismissed:[]},item={id:'ev-1',type:'project',context:'personal',title:'API de crédito',lastUsedAt:'2026-09-10',url:'https://github.com/example/project',description:'API testada'};assert.equal(valid({...base,profile:{python:{l:2,e:0,evidences:[item]}}}),true);assert.equal(valid({...base,profile:{python:{l:2,e:0,evidences:[{...item,url:'javascript:alert(1)'}]}}}),false);});
