const test=require('node:test'),assert=require('node:assert/strict'),E=require('../engine');
const S=[{id:'python',label:'Python',re:/python/},{id:'aws',label:'AWS',re:/aws/},{id:'azure',label:'Azure',re:/azure/}];
const p={python:{l:2,e:3},aws:{l:1,e:2},azure:{l:0,e:0}};
const j={key:'test',role:'Backend Júnior',requirements:['Python','Python básico','Python prático'],differentials:[],tags:['Python'],status:'Ativa',eligible:true,location:'São Paulo',modality:'Remoto'};
test('mandatory unknown blocks applying despite known technology',()=>{const a=E.evaluate({...j,requirements:['Python','Python prático','Experiência com COBOL']},p,S);assert.equal(a.unknown,1);assert.equal(a.canApply,false);assert.ok(a.score<80);});
test('missing mandatory is not hidden by optional matches',()=>{const a=E.evaluate({...j,requirements:['Python','AWS','Azure'],differentials:['Python']},p,S);assert.equal(a.critical,1);assert.equal(a.canApply,false);});
test('no evidence gives no claimed competence',()=>{const a=E.evaluate(j,{python:{l:4,e:0}},S);assert.equal(a.score,0);assert.equal(a.canApply,false);});
test('cloud alternatives allow one provider, conjunction requires both',()=>{assert.equal(E.evaluate({...j,requirements:['AWS ou Azure']},{aws:{l:2,e:3}},S).score,100);assert.equal(E.evaluate({...j,requirements:['AWS e Azure']},{aws:{l:2,e:3}},S).score,0);});
test('affirmative eligibility is never inferred',()=>{const x={...j,role:'Backend Júnior PCD'};assert.equal(E.evaluate(x,p,S).canApply,false);assert.equal(E.evaluate(x,p,S,{}, {test:{eligibility:'yes'}}).canApply,true);});
test('missing dates are not invented or treated as active',()=>{const n=E.normalize({...j,id:1});assert.equal(n.status,'Possivelmente encerrada');assert.equal(n.firstSeenAt,null);});
test('confirmed mandatory and live status can recommend applying',()=>{const a=E.evaluate(j,p,S);assert.equal(a.score,100);assert.equal(a.canApply,true);assert.equal(E.evaluate({...j,status:'Encerrada'},p,S).canApply,false);});
test('stale verification excludes active rankings',()=>{assert.equal(E.normalize({...j,lastVerifiedAt:'2020-01-01'}).status,'Possivelmente encerrada');});
test('seniority in requirements overrides junior title',()=>{assert.equal(E.normalize({...j,requirements:['Python','SQL','Experiência como sênior']}).eligible,false);});
test('intermediate duplicate review is not ranked as eligible',()=>{const n=E.normalize({...j,reviewRequired:true,reviewReason:'Exigências próximas'});assert.equal(n.eligible,false);assert.match(n.qualityIssues.join(' '),/Exigências próximas/);});
test('salary estimate is preserved only when the range is valid',()=>{const n=E.normalize({...j,salary:{kind:'estimate',min:3000,max:4000,median:3000}});assert.equal(n.salary.currency,'BRL');assert.equal(n.salary.max,4000);assert.equal(E.normalize({...j,salary:{kind:'estimate',min:5000,max:3000}}).salary,null);});
test('location and modality gates block incompatible targets',()=>{const a=E.evaluate({...j,modality:'Presencial'},p,S,{location:'Recife'});assert.equal(a.canApply,false);assert.equal(a.label,'Inviável no recorte');});
test('study priority counts jobs entering a qualified application queue',()=>{const requirementsStructured=[
  {text:'Python',requirementType:'mandatory',category:'technical',profileSkillIds:['python'],relation:'single',level:1},
  {text:'Python prático',requirementType:'mandatory',category:'technical',profileSkillIds:['python'],relation:'single',level:1},
  {text:'AWS',requirementType:'mandatory',category:'technical',profileSkillIds:['aws'],relation:'single',level:1},
  {text:'Azure',requirementType:'mandatory',category:'technical',profileSkillIds:['azure'],relation:'single',level:1}
];const profile={python:{l:2,e:3},aws:{l:0,e:0},azure:{l:0,e:0}},a=E.priorities([{...j,requirementsStructured}],profile,S,{},{});assert.equal(a[0].skill.id,'aws');assert.equal(a[0].unlocked,1);assert.equal(a[0].weightedUnlocked,.8);assert.equal(a[0].hoursPerApplication,25);});
test('normalized Spring Boot is not satisfied by generic Java',()=>{const skills=[...S,{id:'java',label:'Java',re:/java/},{id:'spring',label:'Spring Boot',re:/spring/}],profile={...p,java:{l:4,e:4},spring:{l:0,e:0}};const job={...j,requirementsStructured:[{text:'Spring Boot intermediário',mandatory:true,requirementType:'mandatory',category:'technical',profileSkillIds:['spring'],relation:'single',level:2}]};const a=E.evaluate(job,profile,skills);assert.equal(a.rows[0].skills[0].id,'spring');assert.equal(a.rows[0].state,'gap');});
test('unmapped normalized technology stays unknown instead of becoming a gap',()=>{const job={...j,requirementsStructured:[{text:'COBOL',mandatory:true,requirementType:'mandatory',category:'technical',profileSkillIds:[],relation:'single'}]};const a=E.evaluate(job,p,S);assert.equal(a.rows[0].state,'unknown');assert.equal(a.critical,0);assert.equal(a.unknown,1);});
test('normalized alternatives use the best matching exact skill',()=>{const job={...j,requirementsStructured:[{text:'AWS ou Azure',mandatory:true,requirementType:'mandatory',category:'technical',profileSkillIds:['aws','azure'],relation:'any',level:1}]};const a=E.evaluate(job,p,S);assert.equal(a.rows[0].state,'ok');assert.equal(a.score,90);});
test('normalized education is an eliminatory gate, not a technical gap',()=>{const job={...j,requirementsStructured:[{text:'Ensino superior completo',mandatory:true,requirementType:'eliminatory',category:'education',profileSkillIds:[],relation:'single'}]};const unknown=E.evaluate(job,p,S);const met=E.evaluate(job,p,S,{education:'completed'});assert.equal(unknown.gates[0].state,'unknown');assert.equal(unknown.rows.length,0);assert.equal(met.gates[0].state,'ok');});
test('normalized skill without explicit level asks only for fundamentals',()=>{const job={...j,requirementsStructured:[{text:'Python',mandatory:true,requirementType:'mandatory',category:'technical',profileSkillIds:['python'],relation:'single',level:null}]};const a=E.evaluate(job,{python:{l:1,e:3}},S);assert.equal(a.rows[0].state,'ok');assert.equal(a.rows[0].skills[0].req,1);});
test('unmapped side of an alternative does not become a false gap',()=>{const skills=[...S,{id:'spring',label:'Spring Boot',re:/spring/}];const req={text:'Spring Boot ou Jakarta EE',mandatory:true,requirementType:'mandatory',category:'technical',profileSkillIds:['spring'],unmappedSkillCount:1,relation:'any',level:null};const job={...j,requirementsStructured:[req]};assert.equal(E.evaluate(job,{spring:{l:0,e:0}},skills).rows[0].state,'unknown');assert.equal(E.evaluate(job,{spring:{l:1,e:3}},skills).rows[0].state,'ok');});
test('action queue applies now with reasonable known fit and no blocker',()=>{const a=E.evaluate(j,p,S);const d=E.actionDecision(j,a);assert.equal(d.id,'apply_now');assert.equal(d.decisionScore,100);assert.equal(d.confidence,.8);});
test('unknown collection item is not counted as a candidate gap',()=>{const job={...j,requirements:['Python','Python básico','Python prático','COBOL']};const a=E.evaluate(job,p,S),d=E.actionDecision(job,a);assert.equal(a.unknown,1);assert.equal(d.gapCount,0);assert.equal(d.id,'apply_now');assert.match(d.reason,/confirmar/i);});
test('one small gap goes to apply and study in parallel',()=>{const job={...j,requirements:['Python','Python básico','AWS']};const d=E.actionDecision(job,E.evaluate(job,p,S));assert.equal(d.id,'apply_study');assert.equal(d.gapCount,1);assert.ok(d.hours<=20);});
test('two short gaps go to one-to-two-week preparation',()=>{const requirementsStructured=[
  {text:'Python',requirementType:'mandatory',category:'technical',profileSkillIds:['python'],relation:'single',level:1},
  {text:'Python prático',requirementType:'mandatory',category:'technical',profileSkillIds:['python'],relation:'single',level:1},
  {text:'AWS',requirementType:'mandatory',category:'technical',profileSkillIds:['aws'],relation:'single',level:1},
  {text:'Azure',requirementType:'mandatory',category:'technical',profileSkillIds:['azure'],relation:'single',level:1}
];const profile={python:{l:2,e:3},aws:{l:0,e:0},azure:{l:0,e:0}},job={...j,requirementsStructured};const d=E.actionDecision(job,E.evaluate(job,profile,S));assert.equal(d.id,'prepare');assert.equal(d.gapCount,2);assert.equal(d.hours,40);});
test('low-confidence pending LinkedIn vacancy stays in monitoring',()=>{const job={...j,status:'Possivelmente encerrada',validationState:'pending',sourceProvider:'linkedin'};const d=E.actionDecision(job,E.evaluate(job,p,S));assert.equal(d.id,'monitor');assert.equal(d.confidence,.3);assert.match(d.reason,/aberto/i);});
test('eliminatory incompatibility stays in monitoring',()=>{const job={...j,requirementsStructured:[{text:'Ensino superior completo',requirementType:'eliminatory',category:'education',profileSkillIds:[],relation:'single'}]};const a=E.evaluate(job,p,S,{education:'none'}),d=E.actionDecision(job,a);assert.equal(d.id,'monitor');assert.equal(d.blockerCount,1);});
test('closed and excluded vacancies do not enter action queues',()=>{assert.equal(E.actionDecision({...j,status:'Encerrada'},E.evaluate(j,p,S)),null);assert.equal(E.actionDecision({...j,excluded:true},E.evaluate(j,p,S)),null);});
test('study impact weights pending vacancies without treating them as confirmed',()=>{const req=[
  {text:'Python',requirementType:'mandatory',category:'technical',profileSkillIds:['python'],relation:'single',level:1},
  {text:'Python prático',requirementType:'mandatory',category:'technical',profileSkillIds:['python'],relation:'single',level:1},
  {text:'AWS',requirementType:'mandatory',category:'technical',profileSkillIds:['aws'],relation:'single',level:1},
  {text:'Azure',requirementType:'mandatory',category:'technical',profileSkillIds:['azure'],relation:'single',level:1}
],profile={python:{l:2,e:3},aws:{l:0,e:0},azure:{l:0,e:0}},jobs=[
  {...j,key:'official-confirmed',requirementsStructured:req,validationState:'confirmed',sourceOfficial:true},
  {...j,key:'official-pending',requirementsStructured:req,status:'Possivelmente encerrada',validationState:'pending',sourceOfficial:true},
  {...j,key:'linkedin-pending',requirementsStructured:req,status:'Possivelmente encerrada',validationState:'pending',sourceProvider:'linkedin'}
];const aws=E.priorities(jobs,profile,S,{},{}).find(x=>x.skill.id==='aws');assert.equal(aws.frequency,3);assert.equal(aws.weightedFrequency,1.85);assert.equal(aws.unlocked,2);assert.equal(aws.weightedUnlocked,1.55);assert.equal(aws.hoursPerApplication,12.9);});
test('direct qualified applications per hour outrank demand without unlocks',()=>{const skills=[{id:'valuable',label:'Valuable',re:/valuable/},{id:'popular',label:'Popular',re:/popular/}],profile={valuable:{l:0,e:0},popular:{l:0,e:0}},req=id=>[
  {text:'Base',requirementType:'mandatory',category:'technical',profileSkillIds:[],relation:'single'},
  {text:id,requirementType:'mandatory',category:'technical',profileSkillIds:[id],relation:'single',level:1}
];const useful={...j,key:'useful',requirementsStructured:[{text:'Valuable',requirementType:'mandatory',category:'technical',profileSkillIds:['valuable'],relation:'single',level:1},{text:'Valuable prático',requirementType:'mandatory',category:'technical',profileSkillIds:['valuable'],relation:'single',level:1},{text:'Popular',requirementType:'mandatory',category:'technical',profileSkillIds:['popular'],relation:'single',level:1}]};const noisy=[1,2,3].map(n=>({...j,key:'noise'+n,status:'Possivelmente encerrada',validationState:'pending',sourceProvider:'linkedin',requirementsStructured:req('popular')}));const result=E.priorities([useful,...noisy],profile,skills,{},{});assert.equal(result[0].skill.id,'valuable');assert.ok(result[0].applicationsPerHour>0);});
test('application snapshot freezes score, queue and source at submission time',()=>{const a=E.evaluate(j,p,S),d=E.actionDecision(j,a),s=E.applicationSnapshot({...j,sourceName:'Carreiras Acme'},a,d,'2026-08-01T10:00:00Z');assert.equal(s.decisionScore,100);assert.equal(s.queueId,'apply_now');assert.equal(s.sourceName,'Carreiras Acme');assert.equal(s.capturedAt,'2026-08-01T10:00:00Z');});
test('young unanswered application is not a mature negative',()=>{const x={appliedAt:'2026-09-01T00:00:00Z',history:[],matchSnapshot:{decisionScore:85,sourceName:'ATS',queueLabel:'Aplicar agora'}};const f=E.feedbackAnalytics([x],'2026-09-10T00:00:00Z');assert.equal(f.mature,0);assert.equal(f.calibration.ready,false);});
test('rejection is a response and mature outcome but not an interview',()=>{const x={appliedAt:'2026-09-01T00:00:00Z',history:[{stage:'Rejeitado'}],matchSnapshot:{decisionScore:72,sourceName:'ATS',queueLabel:'Aplicar e estudar'}};const f=E.feedbackAnalytics([x],'2026-09-10T00:00:00Z');assert.deepEqual([f.funnel.responses,f.funnel.interviews,f.mature],[1,0,1]);});
test('calibration uses frozen decision score and waits for balanced mature sample',()=>{const make=(score,interview,i)=>({appliedAt:'2026-01-01T00:00:00Z',history:[{stage:interview?'Entrevista RH':'Rejeitado'}],matchSnapshot:{decisionScore:score,sourceName:i%2?'Greenhouse':'Gupy',queueLabel:score>=80?'Aplicar agora':'Aplicar e estudar'}}),apps=[...Array.from({length:6},(_,i)=>make(85,true,i)),...Array.from({length:4},(_,i)=>make(70,i===0,i))],f=E.feedbackAnalytics(apps,'2026-09-10T00:00:00Z');assert.equal(f.calibration.ready,true);assert.equal(f.calibration.status,'promising');assert.equal(f.calibration.high.rate,100);assert.equal(f.calibration.lower.rate,25);assert.equal(f.sources.length,2);assert.equal(f.queues.length,2);});
