begin;

-- Operational ingestion data is intentionally private. Only the backend service
-- role may read or mutate raw third-party payloads.
create table if not exists public.source_registry (
  id text primary key,
  provider text not null,
  display_name text not null,
  base_url text not null,
  priority smallint not null default 3 check (priority between 1 and 5),
  enabled boolean not null default false,
  credentials_required boolean not null default false,
  daily_request_limit integer check (daily_request_limit is null or daily_request_limit > 0),
  lifetime_request_limit integer check (lifetime_request_limit is null or lifetime_request_limit > 0),
  health_status text not null default 'unknown'
    check (health_status in ('unknown','healthy','degraded','unavailable','quota_exhausted','credentials_missing')),
  last_success_at timestamptz,
  last_failure_at timestamptz,
  consecutive_failures integer not null default 0 check (consecutive_failures >= 0),
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.job_candidates (
  candidate_key text primary key,
  provider text not null,
  external_id text,
  source_url text not null,
  apply_url text,
  title_raw text not null default '',
  company_raw text not null default '',
  location_raw text not null default '',
  description_raw text not null default '',
  published_at timestamptz,
  source_updated_at timestamptz,
  first_discovered_at timestamptz not null default now(),
  last_discovered_at timestamptz not null default now(),
  processing_status text not null default 'discovered'
    check (processing_status in ('discovered','qualified','review_required','rejected','published','closed')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  next_retry_at timestamptz,
  rejection_reason text,
  payload_hash text not null,
  dedupe_key text not null,
  qualification jsonb not null default '{}'::jsonb,
  raw_payload jsonb not null default '{}'::jsonb,
  published_job_key text references public.jobs(key) on delete set null,
  unique (provider, external_id)
);

create index if not exists job_candidates_processing_idx
  on public.job_candidates (processing_status, next_retry_at, last_discovered_at desc);
create index if not exists job_candidates_dedupe_idx
  on public.job_candidates (dedupe_key);
create index if not exists job_candidates_provider_idx
  on public.job_candidates (provider, last_discovered_at desc);

create table if not exists public.source_runs (
  id bigint generated by default as identity primary key,
  source_id text not null references public.source_registry(id),
  started_at timestamptz not null,
  finished_at timestamptz not null default now(),
  status text not null check (status in ('success','partial','failed','skipped')),
  request_count integer not null default 0 check (request_count >= 0),
  discovered_count integer not null default 0 check (discovered_count >= 0),
  persisted_count integer not null default 0 check (persisted_count >= 0),
  error_count integer not null default 0 check (error_count >= 0),
  error text,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists source_runs_source_started_idx
  on public.source_runs (source_id, started_at desc);

alter table public.source_registry enable row level security;
alter table public.job_candidates enable row level security;
alter table public.source_runs enable row level security;

revoke all privileges on table public.source_registry from anon, authenticated;
revoke all privileges on table public.job_candidates from anon, authenticated;
revoke all privileges on table public.source_runs from anon, authenticated;
revoke all privileges on sequence public.source_runs_id_seq from anon, authenticated;

grant select, insert, update, delete on table public.source_registry to service_role;
grant select, insert, update, delete on table public.job_candidates to service_role;
grant select, insert, update, delete on table public.source_runs to service_role;
grant usage, select on sequence public.source_runs_id_seq to service_role;

insert into public.source_registry
  (id, provider, display_name, base_url, priority, enabled, credentials_required,
   daily_request_limit, lifetime_request_limit, health_status, metadata)
values
  ('api_br', 'api_br', 'API BR Vagas Aggregator', 'https://apibr.com/vagas/api/v2', 3, true, false,
   null, null, 'unknown', '{"role":"discovery","confidence":"low"}'::jsonb),
  ('adzuna_br', 'adzuna', 'Adzuna Brasil', 'https://api.adzuna.com/v1/api/jobs/br', 3, false, true,
   250, null, 'credentials_missing', '{"role":"discovery","confidence":"medium","requires_terms_review":true}'::jsonb),
  ('jooble_br', 'jooble', 'Jooble Brasil', 'https://br.jooble.org/api', 4, false, true,
   null, 500, 'credentials_missing', '{"role":"targeted_gap_recovery","confidence":"medium"}'::jsonb)
on conflict (id) do update set
  display_name = excluded.display_name,
  base_url = excluded.base_url,
  priority = excluded.priority,
  credentials_required = excluded.credentials_required,
  daily_request_limit = excluded.daily_request_limit,
  lifetime_request_limit = excluded.lifetime_request_limit,
  metadata = public.source_registry.metadata || excluded.metadata,
  updated_at = now();

commit;
